name: build
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    env:
      HUB: containers.istio.tetratelabs.com
      TAG: 1.14.3-tetrate-v0
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: List docker images
        run: bash ./pull.sh
      - name: Scan images for CRITICAL vulnerabilities
        uses: docker://ghcr.io/aquasecurity/trivy
        with:
          # We'd like to use the Github Action here like everywhere else, but it
          # does not support scanning multiple images (yet), so we use the
          # official Trivy image instead, override default entrypoint and run
          # Trivy for every container image in the list. Fail if any image has
          # vulnerabilities.
          entrypoint: /bin/sh
          args: -c "trivy image --clear-cache;trivy image --exit-code 1 --severity HIGH,CRITICAL --no-progress --format sarif -o report.sarif containers.istio.tetratelabs.com/app:1.14.3-tetrate-v0-debug"
      - name: debug
        run: cat report.sarif
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: report.sarif